/*
 * auth basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTokenRequest {
    #[serde(rename = "token")]
    pub token: String,
}

impl GetTokenRequest {
    pub fn new(token: String) -> GetTokenRequest {
        GetTokenRequest { token }
    }
}
