/*
 * auth basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTokenResponse {
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ListTokenResponseItem>,
}

impl ListTokenResponse {
    pub fn new(items: Vec<crate::models::ListTokenResponseItem>) -> ListTokenResponse {
        ListTokenResponse { items }
    }
}
