/*
 * auth basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTokenResponseItem {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "device")]
    pub device: String,
    #[serde(rename = "created")]
    pub created: String,
}

impl ListTokenResponseItem {
    pub fn new(
        token: String,
        platform: String,
        device: String,
        created: String,
    ) -> ListTokenResponseItem {
        ListTokenResponseItem {
            token,
            platform,
            device,
            created,
        }
    }
}
