/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAvailableRequest {
    #[serde(rename = "email")]
    pub email: String,
}

impl AccountAvailableRequest {
    pub fn new(email: String) -> AccountAvailableRequest {
        AccountAvailableRequest { email }
    }
}
