/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountPersonallyIdentifiableInformationResponse {
    #[serde(rename = "account")]
    pub account: Box<crate::models::Account>,
    #[serde(rename = "stats")]
    pub stats: Vec<crate::models::StatsResponse>,
    #[serde(rename = "paymentAudits")]
    pub payment_audits: Box<crate::models::ListAuditResponse>,
}

impl AccountPersonallyIdentifiableInformationResponse {
    pub fn new(
        account: crate::models::Account,
        stats: Vec<crate::models::StatsResponse>,
        payment_audits: crate::models::ListAuditResponse,
    ) -> AccountPersonallyIdentifiableInformationResponse {
        AccountPersonallyIdentifiableInformationResponse {
            account: Box::new(account),
            stats,
            payment_audits: Box::new(payment_audits),
        }
    }
}
