/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteDevicesRequest {
    #[serde(rename = "deviceIds", skip_serializing_if = "Option::is_none")]
    pub device_ids: Option<Vec<String>>,
}

impl Default for DeleteDevicesRequest {
    fn default() -> Self {
        Self::new()
    }
}

impl DeleteDevicesRequest {
    pub fn new() -> DeleteDevicesRequest {
        DeleteDevicesRequest { device_ids: None }
    }
}
