/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAdminsResponse {
    #[serde(rename = "accounts")]
    pub accounts: Vec<crate::models::AccountPortalView>,
}

impl GetAdminsResponse {
    pub fn new(accounts: Vec<crate::models::AccountPortalView>) -> GetAdminsResponse {
        GetAdminsResponse { accounts }
    }
}
