/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemCreateRequest {
    #[serde(rename = "contentId")]
    pub content_id: String,
    #[serde(rename = "properties")]
    pub properties: Vec<crate::models::ItemProperty>,
}

impl ItemCreateRequest {
    pub fn new(
        content_id: String,
        properties: Vec<crate::models::ItemProperty>,
    ) -> ItemCreateRequest {
        ItemCreateRequest {
            content_id,
            properties,
        }
    }
}
