/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordUpdateRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "codeType", skip_serializing_if = "Option::is_none")]
    pub code_type: Option<String>,
}

impl PasswordUpdateRequest {
    pub fn new(email: String) -> PasswordUpdateRequest {
        PasswordUpdateRequest {
            email,
            code_type: None,
        }
    }
}
