/*
 * accounts basic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordUpdateConfirmation {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "newPassword")]
    pub new_password: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl PasswordUpdateConfirmation {
    pub fn new(code: String, new_password: String) -> PasswordUpdateConfirmation {
        PasswordUpdateConfirmation {
            code,
            new_password,
            email: None,
        }
    }
}
