/*
 * inventory object
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArchetypeProxy {
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
}

impl ArchetypeProxy {
    pub fn new(service: String, namespace: String) -> ArchetypeProxy {
        ArchetypeProxy { service, namespace }
    }
}
