/*
 * inventory object
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyPreview {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "originalAmount")]
    pub original_amount: i64,
}

impl CurrencyPreview {
    pub fn new(id: String, amount: i64, original_amount: i64) -> CurrencyPreview {
        CurrencyPreview {
            id,
            amount,
            original_amount,
        }
    }
}
