/*
 * inventory object
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InventoryUpdateRequest {
    #[serde(rename = "currencies", skip_serializing_if = "Option::is_none")]
    pub currencies: Option<::std::collections::HashMap<String, i64>>,
    #[serde(rename = "empty")]
    pub empty: bool,
    #[serde(rename = "currencyProperties", skip_serializing_if = "Option::is_none")]
    pub currency_properties:
        Option<::std::collections::HashMap<String, Vec<crate::models::CurrencyProperty>>>,
    #[serde(rename = "currencyContentIds")]
    pub currency_content_ids: Vec<String>,
    #[serde(rename = "applyVipBonus", skip_serializing_if = "Option::is_none")]
    pub apply_vip_bonus: Option<bool>,
    #[serde(rename = "itemContentIds")]
    pub item_content_ids: Vec<String>,
    #[serde(rename = "updateItems", skip_serializing_if = "Option::is_none")]
    pub update_items: Option<Vec<crate::models::ItemUpdateRequest>>,
    #[serde(rename = "newItems", skip_serializing_if = "Option::is_none")]
    pub new_items: Option<Vec<crate::models::ItemCreateRequest>>,
    #[serde(rename = "transaction", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<String>,
    #[serde(rename = "deleteItems", skip_serializing_if = "Option::is_none")]
    pub delete_items: Option<Vec<crate::models::ItemDeleteRequest>>,
}

impl InventoryUpdateRequest {
    pub fn new(
        empty: bool,
        currency_content_ids: Vec<String>,
        item_content_ids: Vec<String>,
    ) -> InventoryUpdateRequest {
        InventoryUpdateRequest {
            currencies: None,
            empty,
            currency_properties: None,
            currency_content_ids,
            apply_vip_bonus: None,
            item_content_ids,
            update_items: None,
            new_items: None,
            transaction: None,
            delete_items: None,
        }
    }
}
