[package]
name = "bevy_beam_sdk"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Experimental implementation of Beamable SDK into Bevy engine."

[dependencies.bevy]
version = "0.14"
default-features = false
features = ["bevy_ui", "bevy_asset", "bevy_text"]

[dev-dependencies.bevy]
version = "0.14"
default-features = true

[dependencies.beam_autogen_rs]
git = "https://github.com/beamable/beam_autogen_rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bevy_pkv = "0.11"
crossbeam-channel = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tungstenite = { version = "0.24", features = ["native-tls", "handshake"] }
async-compat = "0.2"
mio = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio-tungstenite-wasm = { version = "0.3.1" }

[dependencies.reqwest]
version = "^0.12"
features = ["json", "multipart", "rustls-tls"]
