/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountPersonallyIdentifiableInformationResponse {
    #[serde(rename = "account")]
    pub account: Box<models::Account>,
    #[serde(rename = "stats")]
    pub stats: Vec<models::StatsResponse>,
    #[serde(rename = "paymentAudits")]
    pub payment_audits: Box<models::ListAuditResponse>,
}

impl AccountPersonallyIdentifiableInformationResponse {
    pub fn new(account: models::Account, stats: Vec<models::StatsResponse>, payment_audits: models::ListAuditResponse) -> AccountPersonallyIdentifiableInformationResponse {
        AccountPersonallyIdentifiableInformationResponse {
            account: Box::new(account),
            stats,
            payment_audits: Box::new(payment_audits),
        }
    }
}

