/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountRolesReport {
    #[serde(rename = "accountId")]
    pub account_id: i64,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "realms")]
    pub realms: Vec<models::RealmRolesReport>,
}

impl AccountRolesReport {
    pub fn new(account_id: i64, email: String, realms: Vec<models::RealmRolesReport>) -> AccountRolesReport {
        AccountRolesReport {
            account_id,
            email,
            realms,
        }
    }
}

