/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentRequest {
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "specialization", skip_serializing_if = "Option::is_none")]
    pub specialization: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<i64>,
    #[serde(rename = "action")]
    pub action: String,
}

impl AttachmentRequest {
    pub fn new(symbol: String, action: String) -> AttachmentRequest {
        AttachmentRequest {
            quantity: None,
            symbol,
            specialization: None,
            target: None,
            action,
        }
    }
}

