/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Attachment {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "wrapped")]
    pub wrapped: Box<models::EntitlementGenerator>,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<i64>,
}

impl Attachment {
    pub fn new(id: i64, wrapped: models::EntitlementGenerator, state: String) -> Attachment {
        Attachment {
            id,
            wrapped: Box::new(wrapped),
            state,
            target: None,
        }
    }
}

