/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteInFlightRequest {
    #[serde(rename = "inFlightFailureIds")]
    pub in_flight_failure_ids: Vec<String>,
}

impl BatchDeleteInFlightRequest {
    pub fn new(in_flight_failure_ids: Vec<String>) -> BatchDeleteInFlightRequest {
        BatchDeleteInFlightRequest {
            in_flight_failure_ids,
        }
    }
}

