/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchSetStatsRequest {
    #[serde(rename = "updates")]
    pub updates: Vec<models::StatUpdateRequest>,
}

impl BatchSetStatsRequest {
    pub fn new(updates: Vec<models::StatUpdateRequest>) -> BatchSetStatsRequest {
        BatchSetStatsRequest {
            updates,
        }
    }
}

