/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoLimits {
    #[serde(rename = "maxContainerSize")]
    pub max_container_size: String,
    #[serde(rename = "maxRunningContainersPerService")]
    pub max_running_containers_per_service: i32,
}

impl BeamoLimits {
    pub fn new(max_container_size: String, max_running_containers_per_service: i32) -> BeamoLimits {
        BeamoLimits {
            max_container_size,
            max_running_containers_per_service,
        }
    }
}

