/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeginPurchaseRequest {
    #[serde(rename = "purchaseId")]
    pub purchase_id: String,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl BeginPurchaseRequest {
    pub fn new(purchase_id: String) -> BeginPurchaseRequest {
        BeginPurchaseRequest {
            purchase_id,
            language: None,
            time: None,
        }
    }
}

