/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientPermission {
    #[serde(rename = "write_self")]
    pub write_self: bool,
}

impl ClientPermission {
    pub fn new(write_self: bool) -> ClientPermission {
        ClientPermission {
            write_self,
        }
    }
}

