/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonResponse {
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, String>,
}

impl CommonResponse {
    pub fn new(result: String, data: std::collections::HashMap<String, String>) -> CommonResponse {
        CommonResponse {
            result,
            data,
        }
    }
}

