/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentDefinition {
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "checksum")]
    pub checksum: String,
    #[serde(rename = "properties")]
    pub properties: std::collections::HashMap<String, models::ContentMeta>,
    #[serde(rename = "variants", skip_serializing_if = "Option::is_none")]
    pub variants: Option<Vec<std::collections::HashMap<String, models::ContentMeta>>>,
}

impl ContentDefinition {
    pub fn new(prefix: String, id: String, checksum: String, properties: std::collections::HashMap<String, models::ContentMeta>) -> ContentDefinition {
        ContentDefinition {
            prefix,
            tags: None,
            id,
            checksum,
            properties,
            variants: None,
        }
    }
}

