/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "content")]
    Content,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "binary")]
    Binary,

}

impl std::fmt::Display for ContentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Content => write!(f, "content"),
            Self::Text => write!(f, "text"),
            Self::Binary => write!(f, "binary"),
        }
    }
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::Content
    }
}

