/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentLimits {
    #[serde(rename = "maxDistinctContentIds", skip_serializing_if = "Option::is_none")]
    pub max_distinct_content_ids: Option<i32>,
}

impl ContentLimits {
    pub fn new() -> ContentLimits {
        ContentLimits {
            max_distinct_content_ids: None,
        }
    }
}

