/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoomRequest {
    #[serde(rename = "roomName")]
    pub room_name: String,
    #[serde(rename = "keepSubscribed")]
    pub keep_subscribed: bool,
    #[serde(rename = "players")]
    pub players: Vec<i64>,
}

impl CreateRoomRequest {
    pub fn new(room_name: String, keep_subscribed: bool, players: Vec<i64>) -> CreateRoomRequest {
        CreateRoomRequest {
            room_name,
            keep_subscribed,
            players,
        }
    }
}

