/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDonationRequest {
    #[serde(rename = "currencyId")]
    pub currency_id: String,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
}

impl CreateDonationRequest {
    pub fn new(currency_id: String, amount: i64) -> CreateDonationRequest {
        CreateDonationRequest {
            currency_id,
            amount,
            config: None,
        }
    }
}

