/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerView {
    #[serde(rename = "cid")]
    pub cid: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "projects")]
    pub projects: Vec<models::ProjectView>,
}

impl CustomerView {
    pub fn new(cid: i64, name: String, projects: Vec<models::ProjectView>) -> CustomerView {
        CustomerView {
            cid,
            name,
            alias: None,
            projects,
        }
    }
}

