/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataPoint {
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl DataPoint {
    pub fn new(timestamp: String, value: String) -> DataPoint {
        DataPoint {
            timestamp,
            value,
        }
    }
}

