/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataDomain {
    #[serde(rename = "messageBusAnalytics", skip_serializing_if = "Option::is_none")]
    pub message_bus_analytics: Option<Vec<String>>,
    #[serde(rename = "mongoSrvAddress", skip_serializing_if = "Option::is_none")]
    pub mongo_srv_address: Option<String>,
    #[serde(rename = "memcachedHosts")]
    pub memcached_hosts: Vec<String>,
    #[serde(rename = "mongoSharded")]
    pub mongo_sharded: bool,
    #[serde(rename = "mongoSSL", skip_serializing_if = "Option::is_none")]
    pub mongo_ssl: Option<bool>,
    #[serde(rename = "mongoHosts")]
    pub mongo_hosts: Vec<String>,
    #[serde(rename = "mongoSSLEnabled")]
    pub mongo_ssl_enabled: bool,
    #[serde(rename = "messageBusCommon", skip_serializing_if = "Option::is_none")]
    pub message_bus_common: Option<Vec<String>>,
    #[serde(rename = "redisShards", skip_serializing_if = "Option::is_none")]
    pub redis_shards: Option<Vec<models::RedisShard>>,
}

impl DataDomain {
    pub fn new(memcached_hosts: Vec<String>, mongo_sharded: bool, mongo_hosts: Vec<String>, mongo_ssl_enabled: bool) -> DataDomain {
        DataDomain {
            message_bus_analytics: None,
            mongo_srv_address: None,
            memcached_hosts,
            mongo_sharded,
            mongo_ssl: None,
            mongo_hosts,
            mongo_ssl_enabled,
            message_bus_common: None,
            redis_shards: None,
        }
    }
}

