/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventScoreRequest {
    #[serde(rename = "eventId")]
    pub event_id: String,
    #[serde(rename = "score")]
    pub score: f64,
    #[serde(rename = "increment", skip_serializing_if = "Option::is_none")]
    pub increment: Option<bool>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<std::collections::HashMap<String, String>>,
}

impl EventScoreRequest {
    pub fn new(event_id: String, score: f64) -> EventScoreRequest {
        EventScoreRequest {
            event_id,
            score,
            increment: None,
            stats: None,
        }
    }
}

