/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventClaimResponse {
    #[serde(rename = "view")]
    pub view: Box<models::EventPlayerStateView>,
    #[serde(rename = "gameRspJson")]
    pub game_rsp_json: String,
}

impl EventClaimResponse {
    pub fn new(view: models::EventPlayerStateView, game_rsp_json: String) -> EventClaimResponse {
        EventClaimResponse {
            view: Box::new(view),
            game_rsp_json,
        }
    }
}

