/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventsInDateRangeResponse {
    #[serde(rename = "eventInDateRange")]
    pub event_in_date_range: Vec<models::EventDateRanges>,
}

impl EventsInDateRangeResponse {
    pub fn new(event_in_date_range: Vec<models::EventDateRanges>) -> EventsInDateRangeResponse {
        EventsInDateRangeResponse {
            event_in_date_range,
        }
    }
}

