/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamerTagAssociation {
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "gamerTag")]
    pub gamer_tag: i64,
}

impl GamerTagAssociation {
    pub fn new(project_id: String, gamer_tag: i64) -> GamerTagAssociation {
        GamerTagAssociation {
            project_id,
            gamer_tag,
        }
    }
}

