/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGroupStatusResponse {
    #[serde(rename = "statuses")]
    pub statuses: Vec<models::GroupStatus>,
}

impl GetGroupStatusResponse {
    pub fn new(statuses: Vec<models::GroupStatus>) -> GetGroupStatusResponse {
        GetGroupStatusResponse {
            statuses,
        }
    }
}

