/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSignedUrlResponse {
    #[serde(rename = "headers")]
    pub headers: Vec<models::GetLogsUrlHeader>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "method")]
    pub method: String,
}

impl GetSignedUrlResponse {
    pub fn new(headers: Vec<models::GetLogsUrlHeader>, url: String, body: String, method: String) -> GetSignedUrlResponse {
        GetSignedUrlResponse {
            headers,
            url,
            body,
            method,
        }
    }
}

