/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatusForGroupsRequest {
    #[serde(rename = "groupIds")]
    pub group_ids: Vec<i64>,
    #[serde(rename = "contentId")]
    pub content_id: String,
}

impl GetStatusForGroupsRequest {
    pub fn new(group_ids: Vec<i64>, content_id: String) -> GetStatusForGroupsRequest {
        GetStatusForGroupsRequest {
            group_ids,
            content_id,
        }
    }
}

