/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupScoreBinding {
    #[serde(rename = "board")]
    pub board: String,
    #[serde(rename = "derivatives")]
    pub derivatives: Vec<String>,
    #[serde(rename = "score")]
    pub score: i64,
}

impl GroupScoreBinding {
    pub fn new(board: String, derivatives: Vec<String>, score: i64) -> GroupScoreBinding {
        GroupScoreBinding {
            board,
            derivatives,
            score,
        }
    }
}

