/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupMemberInfo {
    #[serde(rename = "guild", skip_serializing_if = "Option::is_none")]
    pub guild: Option<Vec<models::GroupUserMember>>,
    #[serde(rename = "subgroup", skip_serializing_if = "Option::is_none")]
    pub subgroup: Option<Vec<models::GroupUserMember>>,
}

impl GroupMemberInfo {
    pub fn new() -> GroupMemberInfo {
        GroupMemberInfo {
            guild: None,
            subgroup: None,
        }
    }
}

