/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupInvite {
    #[serde(rename = "gamerTag")]
    pub gamer_tag: i64,
    #[serde(rename = "subGroup", skip_serializing_if = "Option::is_none")]
    pub sub_group: Option<i64>,
    #[serde(rename = "useNewRewardsSystem", skip_serializing_if = "Option::is_none")]
    pub use_new_rewards_system: Option<bool>,
}

impl GroupInvite {
    pub fn new(gamer_tag: i64) -> GroupInvite {
        GroupInvite {
            gamer_tag,
            sub_group: None,
            use_new_rewards_system: None,
        }
    }
}

