/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportFriendsRequest {
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl ImportFriendsRequest {
    pub fn new(source: String, token: String) -> ImportFriendsRequest {
        ImportFriendsRequest {
            source,
            token,
        }
    }
}

