/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemContentResponse {
    #[serde(rename = "content")]
    pub content: Vec<models::ItemArchetype>,
}

impl ItemContentResponse {
    pub fn new(content: Vec<models::ItemArchetype>) -> ItemContentResponse {
        ItemContentResponse {
            content,
        }
    }
}

