/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemGroup {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "items")]
    pub items: Vec<models::Item>,
}

impl ItemGroup {
    pub fn new(id: String, items: Vec<models::Item>) -> ItemGroup {
        ItemGroup {
            id,
            items,
        }
    }
}

