/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobRetryPolicy {
    #[serde(rename = "maxRetryCount", skip_serializing_if = "Option::is_none")]
    pub max_retry_count: Option<i32>,
    #[serde(rename = "retryDelayMs", skip_serializing_if = "Option::is_none")]
    pub retry_delay_ms: Option<i32>,
    #[serde(rename = "useExponentialBackoff", skip_serializing_if = "Option::is_none")]
    pub use_exponential_backoff: Option<bool>,
}

impl JobRetryPolicy {
    pub fn new() -> JobRetryPolicy {
        JobRetryPolicy {
            max_retry_count: None,
            retry_delay_ms: None,
            use_exponential_backoff: None,
        }
    }
}

