/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeaderboardGetMatchRequest {
    #[serde(rename = "poolSize")]
    pub pool_size: i32,
    #[serde(rename = "windows")]
    pub windows: i32,
    #[serde(rename = "windowSize")]
    pub window_size: i32,
}

impl LeaderboardGetMatchRequest {
    pub fn new(pool_size: i32, windows: i32, window_size: i32) -> LeaderboardGetMatchRequest {
        LeaderboardGetMatchRequest {
            pool_size,
            windows,
            window_size,
        }
    }
}

