/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeaderboardPlayerAssignmentRequest {
    #[serde(rename = "boardId")]
    pub board_id: String,
    #[serde(rename = "joinBoard", skip_serializing_if = "Option::is_none")]
    pub join_board: Option<bool>,
}

impl LeaderboardPlayerAssignmentRequest {
    pub fn new(board_id: String) -> LeaderboardPlayerAssignmentRequest {
        LeaderboardPlayerAssignmentRequest {
            board_id,
            join_board: None,
        }
    }
}

