/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTagsRequest {
    #[serde(rename = "tagNameFilter", skip_serializing_if = "Option::is_none")]
    pub tag_name_filter: Option<String>,
}

impl ListTagsRequest {
    pub fn new() -> ListTagsRequest {
        ListTagsRequest {
            tag_name_filter: None,
        }
    }
}

