/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalizedPrice {
    #[serde(rename = "to")]
    pub to: i64,
    #[serde(rename = "price")]
    pub price: i64,
    #[serde(rename = "priceLocalized")]
    pub price_localized: f64,
    #[serde(rename = "priceLocalizedString")]
    pub price_localized_string: String,
}

impl LocalizedPrice {
    pub fn new(to: i64, price: i64, price_localized: f64, price_localized_string: String) -> LocalizedPrice {
        LocalizedPrice {
            to,
            price,
            price_localized,
            price_localized_string,
        }
    }
}

