/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchMakingWindowResp {
    #[serde(rename = "difficulty")]
    pub difficulty: i32,
    #[serde(rename = "matches")]
    pub matches: Vec<models::MatchMakingRanking>,
}

impl MatchMakingWindowResp {
    pub fn new(difficulty: i32, matches: Vec<models::MatchMakingRanking>) -> MatchMakingWindowResp {
        MatchMakingWindowResp {
            difficulty,
            matches,
        }
    }
}

