/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferConstraint {
    #[serde(rename = "constraint")]
    pub constraint: String,
    #[serde(rename = "value")]
    pub value: i32,
}

impl OfferConstraint {
    pub fn new(constraint: String, value: i32) -> OfferConstraint {
        OfferConstraint {
            constraint,
            value,
        }
    }
}

