/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnlineStatusRequest {
    #[serde(rename = "playerIds")]
    pub player_ids: String,
    #[serde(rename = "intervalSecs")]
    pub interval_secs: i64,
}

impl OnlineStatusRequest {
    pub fn new(player_ids: String, interval_secs: i64) -> OnlineStatusRequest {
        OnlineStatusRequest {
            player_ids,
            interval_secs,
        }
    }
}

