/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaNamespace {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PaNamespace {
    pub fn new(namespace: String, r#type: String) -> PaNamespace {
        PaNamespace {
            namespace,
            r#type,
        }
    }
}

