/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayersStatusResponse {
    #[serde(rename = "playersStatus", skip_serializing_if = "Option::is_none")]
    pub players_status: Option<Vec<models::OnlineStatus>>,
}

impl PlayersStatusResponse {
    pub fn new() -> PlayersStatusResponse {
        PlayersStatusResponse {
            players_status: None,
        }
    }
}

