/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PresenceStatus {
    #[serde(rename = "Visible")]
    Visible,
    #[serde(rename = "Invisible")]
    Invisible,
    #[serde(rename = "Dnd")]
    Dnd,
    #[serde(rename = "Away")]
    Away,

}

impl std::fmt::Display for PresenceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Visible => write!(f, "Visible"),
            Self::Invisible => write!(f, "Invisible"),
            Self::Dnd => write!(f, "Dnd"),
            Self::Away => write!(f, "Away"),
        }
    }
}

impl Default for PresenceStatus {
    fn default() -> PresenceStatus {
        Self::Visible
    }
}

