/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromoteRealmResponse {
    #[serde(rename = "sourcePid")]
    pub source_pid: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<models::PromotionScope>,
}

impl PromoteRealmResponse {
    pub fn new(source_pid: String, scopes: Vec<models::PromotionScope>) -> PromoteRealmResponse {
        PromoteRealmResponse {
            source_pid,
            scopes,
        }
    }
}

