/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmConfigResponse {
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, String>,
}

impl RealmConfigResponse {
    pub fn new(config: std::collections::HashMap<String, String>) -> RealmConfigResponse {
        RealmConfigResponse {
            config,
        }
    }
}

