/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportPurchaseRequest {
    #[serde(rename = "listingId")]
    pub listing_id: String,
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<bool>,
}

impl ReportPurchaseRequest {
    pub fn new(listing_id: String) -> ReportPurchaseRequest {
        ReportPurchaseRequest {
            listing_id,
            free: None,
        }
    }
}

