/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteParameters {
    #[serde(rename = "parameters")]
    pub parameters: Vec<models::RouteParameter>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    #[serde(rename = "objectId", skip_serializing_if = "Option::is_none")]
    pub object_id: Option<String>,
}

impl RouteParameters {
    pub fn new(parameters: Vec<models::RouteParameter>) -> RouteParameters {
        RouteParameters {
            parameters,
            payload: None,
            object_id: None,
        }
    }
}

