/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaveCatalogRequest {
    #[serde(rename = "stores")]
    pub stores: Vec<models::Store>,
    #[serde(rename = "offerDefinitions")]
    pub offer_definitions: Vec<models::OfferDefinition>,
}

impl SaveCatalogRequest {
    pub fn new(stores: Vec<models::Store>, offer_definitions: Vec<models::OfferDefinition>) -> SaveCatalogRequest {
        SaveCatalogRequest {
            stores,
            offer_definitions,
        }
    }
}

