/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchExtendedResponse {
    #[serde(rename = "gamerStats")]
    pub gamer_stats: std::collections::HashMap<String, std::collections::HashMap<String, String>>,
}

impl SearchExtendedResponse {
    pub fn new(gamer_stats: std::collections::HashMap<String, std::collections::HashMap<String, String>>) -> SearchExtendedResponse {
        SearchExtendedResponse {
            gamer_stats,
        }
    }
}

