/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceDependencyReference {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "storageType")]
    pub storage_type: String,
}

impl ServiceDependencyReference {
    pub fn new(id: String, storage_type: String) -> ServiceDependencyReference {
        ServiceDependencyReference {
            id,
            storage_type,
        }
    }
}

