/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceStorageStatus {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "storageType")]
    pub storage_type: String,
    #[serde(rename = "isRunning")]
    pub is_running: bool,
    #[serde(rename = "isCurrent")]
    pub is_current: bool,
}

impl ServiceStorageStatus {
    pub fn new(id: String, storage_type: String, is_running: bool, is_current: bool) -> ServiceStorageStatus {
        ServiceStorageStatus {
            id,
            storage_type,
            is_running,
            is_current,
        }
    }
}

