/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionHistoryRequest {
    #[serde(rename = "dbid")]
    pub dbid: i64,
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<i32>,
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
}

impl SessionHistoryRequest {
    pub fn new(dbid: i64) -> SessionHistoryRequest {
        SessionHistoryRequest {
            dbid,
            month: None,
            year: None,
        }
    }
}

