/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SkuDefinitions {
    #[serde(rename = "version")]
    pub version: i64,
    /// Milliseconds since midnight, January 1, 1970 UTC
    #[serde(rename = "created")]
    pub created: i64,
    #[serde(rename = "definitions")]
    pub definitions: Vec<models::Sku>,
}

impl SkuDefinitions {
    pub fn new(version: i64, created: i64, definitions: Vec<models::Sku>) -> SkuDefinitions {
        SkuDefinitions {
            version,
            created,
            definitions,
        }
    }
}

