/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsSubscribeRequest {
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<String>,
}

impl StatsSubscribeRequest {
    pub fn new(service: String, subscriptions: Vec<String>) -> StatsSubscribeRequest {
        StatsSubscribeRequest {
            service,
            subscriptions,
        }
    }
}

