/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatUpdateRequestStringListFormat {
    #[serde(rename = "set", skip_serializing_if = "Option::is_none")]
    pub set: Option<Vec<models::StatStringListEntry>>,
}

impl StatUpdateRequestStringListFormat {
    pub fn new() -> StatUpdateRequestStringListFormat {
        StatUpdateRequestStringListFormat {
            set: None,
        }
    }
}

