/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionVerificationRequest {
    #[serde(rename = "hubMode")]
    pub hub_mode: String,
    #[serde(rename = "hubChallenge")]
    pub hub_challenge: String,
    #[serde(rename = "hubVerifyToken")]
    pub hub_verify_token: String,
}

impl SubscriptionVerificationRequest {
    pub fn new(hub_mode: String, hub_challenge: String, hub_verify_token: String) -> SubscriptionVerificationRequest {
        SubscriptionVerificationRequest {
            hub_mode,
            hub_challenge,
            hub_verify_token,
        }
    }
}

