/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionVerificationResponse {
    #[serde(rename = "hubChallenge")]
    pub hub_challenge: String,
}

impl SubscriptionVerificationResponse {
    pub fn new(hub_challenge: String) -> SubscriptionVerificationResponse {
        SubscriptionVerificationResponse {
            hub_challenge,
        }
    }
}

