/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThirdPartyAvailableRequest {
    #[serde(rename = "thirdParty")]
    pub third_party: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl ThirdPartyAvailableRequest {
    pub fn new(third_party: String, token: String) -> ThirdPartyAvailableRequest {
        ThirdPartyAvailableRequest {
            third_party,
            token,
        }
    }
}

