/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TournamentQueryRequest {
    #[serde(rename = "isRunning", skip_serializing_if = "Option::is_none")]
    pub is_running: Option<bool>,
    #[serde(rename = "contentId", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    #[serde(rename = "cycle", skip_serializing_if = "Option::is_none")]
    pub cycle: Option<i32>,
}

impl TournamentQueryRequest {
    pub fn new() -> TournamentQueryRequest {
        TournamentQueryRequest {
            is_running: None,
            content_id: None,
            cycle: None,
        }
    }
}

