/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateListingCooldownRequest {
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "cooldownReduction")]
    pub cooldown_reduction: i32,
}

impl UpdateListingCooldownRequest {
    pub fn new(symbol: String, cooldown_reduction: i32) -> UpdateListingCooldownRequest {
        UpdateListingCooldownRequest {
            symbol,
            cooldown_reduction,
        }
    }
}

