/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGameHierarchyRequest {
    #[serde(rename = "rootPID")]
    pub root_pid: String,
    #[serde(rename = "projects")]
    pub projects: Vec<models::ProjectView>,
}

impl UpdateGameHierarchyRequest {
    pub fn new(root_pid: String, projects: Vec<models::ProjectView>) -> UpdateGameHierarchyRequest {
        UpdateGameHierarchyRequest {
            root_pid,
            projects,
        }
    }
}

