/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadRequestFromPortal {
    #[serde(rename = "objectKey")]
    pub object_key: String,
    #[serde(rename = "sizeInBytes")]
    pub size_in_bytes: i64,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Vec<models::MetadataPair>>,
    #[serde(rename = "lastModified", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<i64>,
}

impl UploadRequestFromPortal {
    pub fn new(object_key: String, size_in_bytes: i64) -> UploadRequestFromPortal {
        UploadRequestFromPortal {
            object_key,
            size_in_bytes,
            metadata: None,
            last_modified: None,
        }
    }
}

