/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadTrialDataRequest {
    #[serde(rename = "trialName")]
    pub trial_name: String,
    #[serde(rename = "cohortName")]
    pub cohort_name: String,
    #[serde(rename = "dataName")]
    pub data_name: String,
    #[serde(rename = "filePayloadBase64")]
    pub file_payload_base64: String,
}

impl UploadTrialDataRequest {
    pub fn new(trial_name: String, cohort_name: String, data_name: String, file_payload_base64: String) -> UploadTrialDataRequest {
        UploadTrialDataRequest {
            trial_name,
            cohort_name,
            data_name,
            file_payload_base64,
        }
    }
}

