/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UrlResponse {
    #[serde(rename = "serviceName")]
    pub service_name: String,
    #[serde(rename = "s3URLs")]
    pub s3_urls: Vec<models::UploadUrl>,
}

impl UrlResponse {
    pub fn new(service_name: String, s3_urls: Vec<models::UploadUrl>) -> UrlResponse {
        UrlResponse {
            service_name,
            s3_urls,
        }
    }
}

