/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebSocketConfiguration {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

impl WebSocketConfiguration {
    pub fn new(provider: String) -> WebSocketConfiguration {
        WebSocketConfiguration {
            provider,
            uri: None,
        }
    }
}

