/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookReward {
    #[serde(rename = "webhookSymbol", skip_serializing_if = "Option::is_none")]
    pub webhook_symbol: Option<String>,
    #[serde(rename = "strategy")]
    pub strategy: Box<models::WebhookInvocationStrategy>,
    #[serde(rename = "webHookComet", skip_serializing_if = "Option::is_none")]
    pub web_hook_comet: Option<Box<models::WebhookComet>>,
}

impl WebhookReward {
    pub fn new(strategy: models::WebhookInvocationStrategy) -> WebhookReward {
        WebhookReward {
            webhook_symbol: None,
            strategy: Box::new(strategy),
            web_hook_comet: None,
        }
    }
}

