/*
 * Auth Actor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookInvocationStrategy {
    #[serde(rename = "invocationType")]
    pub invocation_type: models::WebhookInvocationType,
    #[serde(rename = "retryType")]
    pub retry_type: models::WebhookRetryType,
}

impl WebhookInvocationStrategy {
    pub fn new(invocation_type: models::WebhookInvocationType, retry_type: models::WebhookRetryType) -> WebhookInvocationStrategy {
        WebhookInvocationStrategy {
            invocation_type,
            retry_type,
        }
    }
}

