/*
 * ForgeService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamablePeriodCommonPeriodContentPeriodSerializableDictionaryStringToString {
    #[serde(rename = "keys")]
    pub keys: Vec<String>,
    #[serde(rename = "values")]
    pub values: Vec<String>,
}

impl BeamablePeriodCommonPeriodContentPeriodSerializableDictionaryStringToString {
    pub fn new(
        keys: Vec<String>,
        values: Vec<String>,
    ) -> BeamablePeriodCommonPeriodContentPeriodSerializableDictionaryStringToString {
        BeamablePeriodCommonPeriodContentPeriodSerializableDictionaryStringToString { keys, values }
    }
}
