/*
 * ForgeService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemCreateRequest {
    #[serde(rename = "contentId")]
    pub content_id: String,
    #[serde(rename = "properties")]
    pub properties: Box<
        crate::models::BeamablePeriodCommonPeriodContentPeriodSerializableDictionaryStringToString,
    >,
    #[serde(rename = "requestId")]
    pub request_id: String,
}

impl BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemCreateRequest {
    pub fn new(
        content_id: String,
        properties: crate::models::BeamablePeriodCommonPeriodContentPeriodSerializableDictionaryStringToString,
        request_id: String,
    ) -> BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemCreateRequest {
        BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemCreateRequest {
            content_id,
            properties: Box::new(properties),
            request_id,
        }
    }
}
