/*
 * ForgeService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemDeleteRequest {
    #[serde(rename = "contentId")]
    pub content_id: String,
    #[serde(rename = "proxyId")]
    pub proxy_id: String,
}

impl BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemDeleteRequest {
    pub fn new(
        content_id: String,
        proxy_id: String,
    ) -> BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemDeleteRequest {
        BeamablePeriodCommonPeriodApiPeriodInventoryPeriodFederatedItemDeleteRequest {
            content_id,
            proxy_id,
        }
    }
}
