name: WebGL build

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  web_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency: 
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            bevy_forge/target/
          key: ${{ github.ref || github.run_id }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
          components: clippy,rustfmt
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: wasm-bindgen-cli@0.2.99
      - name: Install Linux dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: ${{ runner.os == 'linux' }}
        with:
          packages: libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Check
        run: just check
      - name: Web Build
        run: just web_build
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          SQUASH_HISTORY: true
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
